import Head from 'next/head'

import mainstyles from '../styles/index.module.css'

export default function Home() {
  return (
    <div className={mainstyles.landingMain}>
      <Head>
        <meta charset="UTF-8" />
        <title>SAWO NEXT.JS SAMPLE APP</title>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={mainstyles.landingMain}>
        <header>
          <div className={mainstyles.container}>
            <div className={mainstyles.nav_m}>
              <div className={mainstyles.nav}>
                <nav
                  className="nav_m nav navbar navbar-expand-lg navbar-light primary-menu"
                >
                  <a href="/" className={mainstyles.navbarbrand}>
                    <img className={mainstyles.navbar_logo}
                      src="/logo.jpg" alt="Logo" />
                  </a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"
                    onclick="onToggle()">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div className="navbar_nav ml-auto d-flex justify-content-between">
                      <span className="d-flex">
                        <a href="/" className="nav-link active styling__nav__link">
                          Home
                        </a>

                        <a href="/" className="nav-link styling__nav__link"> Pricing </a>

                        <a href="/" className="nav-link styling__nav__link"> Docs </a>

                        <a href="/" className="nav-link styling__nav__link">
                          Resources
                        </a>

                        <a href="/" className="nav-link styling__nav__link">
                          Contact Us
                        </a>
                      </span>
                      <span>
                        <a href="/login" className="btn btn-warning">
                          Login <i class="fa fa-sign-in" aria-hidden="true"></i>
                        </a>
                      </span>
                    </div>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </header>
        <main className={mainstyles.main}>
          <div className={mainstyles.heading}>
            <h1>Product Headline</h1>
            <div className={mainstyles.cta}>
              <button className="btn btn-lg btn-warning mt-3 cta">
                <span>Call To Action</span>
              </button>
            </div>
          </div>
          <div className={mainstyles.feature_cards}>
            <div className="feature_cards row">
              <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="card mb-4 mx-auto">
                  <div class="card-body">
                    <h5 class="card-title">Feature 1</h5>
                    <p class="card-text">
                      Some quick example text to build on the card title and make up
                      the bulk of the card's content.
                    </p>

                    <a href="/" class="btn btn-warning"> Go somewhere </a>
                  </div>
                </div>
              </div>
              <div className="col-xs-12 col-sm-6 col-md-4">
                <div className="card mb-4 mx-auto">
                  <div className="card-body">
                    <h5 className="card-title">Feature 2</h5>
                    <p className="card-text">
                      Some quick example text to build on the card title and make up
                      the bulk of the card's content.
                    </p>

                    <a href="/" className="btn btn-warning"> Go somewhere </a>
                  </div>
                </div>
              </div>
              <div className="col-xs-12 col-sm-6 col-md-4">
                <div className="card mb-4 mx-auto">
                  <div className="card-body">
                    <h5 className="card-title">Feature 3</h5>
                    <p className="card-text">
                      Some quick example text to build on the card title and make up
                      the bulk of the card's content.
                    </p>

                    <a href="/" className="btn btn-warning"> Go somewhere </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
        <footer />
      </div >

    </div >


  )
}
/*
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
*/